//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Develop.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public string ID { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<int> UsersID { get; set; }
        public Nullable<long> TotalPrice { get; set; }
        public Nullable<System.DateTime> Createddate { get; set; }
        public bool IsDeleted { get; set; }
    }
}
